export default Object.freeze({
    LOGIN: 'LoginScreen',
    REGISTER: 'RegisterScreen',
    STARTER: 'Starter',
    ASSOCIATION_LIST: 'ListAssociationScreen',
    NEW_ASSOCIATION: 'NewAssociationScreen',
    EDIT_MEMBER: 'EditMemberScreen',
    NEW_COTISATION: 'NewCotisationScreen',
    LIST_ENGAGEMENT: 'ListEngagementScreen',
    NEW_ENGAGEMENT: 'NewEngagementScreen',
    NEW_INFO: 'NewInformations',
    NEW_ADHESION: 'NouvelleAdhesionScreen',
    USER_COMPTE: 'UserCompte',
    EDIT_USER_COMPTE: 'EditUserCompte',
    NEW_ENGAGEMENT_LIST: 'NewEngagementList',
    ASSOCIATION_DETAILS: 'AssociationDetailScreen',
    TRANSACTION: 'Transaction',
    NEW_TRANSACTION: 'NewTransaction',
    TRANSACTION_: 'TransactionDetail',
    TRANSACTION_DETAIL: 'TransactionDetail',
    VALIDATION_TRANSAC_DETAIL: 'ValidationTransacDetail',
    EDITI_TRANSACTION: 'EditTransaction',
    HELP: 'HelpScreen',
    LIST_COTISATION: 'ListCotisation',
    PAYEMENT_COTISATION: 'PayementCotisation'
})